# Generated by Django 5.1.4 on 2025-01-10 14:05

import libs.truncate_table_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_appid', models.IntegerField(verbose_name='APPID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short_description', models.CharField(max_length=255, verbose_name='Резюме')),
                ('metacritic', models.IntegerField(verbose_name='Оценка')),
                ('metacritic_link', models.CharField(max_length=255, verbose_name='Metacritic ссылка')),
                ('release_date', models.CharField(max_length=255, verbose_name='Дата выхода')),
                ('developers', models.CharField(max_length=255, verbose_name='Разработчики')),
                ('publishers', models.CharField(max_length=255, verbose_name='Издатели')),
                ('genres', models.CharField(max_length=255, verbose_name='Жанры')),
                ('categories', models.CharField(max_length=255, verbose_name='Категории')),
                ('header_image', models.CharField(max_length=255, verbose_name='Изображение')),
                ('background', models.CharField(max_length=255, verbose_name='Фон')),
                ('time', models.FloatField(default=0, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ('name',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
    ]
