# Generated by Django 5.1.4 on 2025-01-11 11:42

import libs.truncate_table_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_category_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Разработчик',
                'verbose_name_plural': 'Разработчики',
                'ordering': ('name',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
                'ordering': ('name',),
            },
            bases=(libs.truncate_table_mixin.TruncateTableMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='game',
            name='background',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фон'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='game',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genres',
        ),
        migrations.AlterField(
            model_name='game',
            name='header_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='game',
            name='metacritic',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='game',
            name='metacritic_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Metacritic ссылка'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='publishers',
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='game.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(blank=True, null=True, to='game.developer', verbose_name='Разработчики'),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='game.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(blank=True, null=True, to='game.publisher', verbose_name='Издатели'),
        ),
    ]
