# Generated by Django 5.1.4 on 2025-01-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_last_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
    ]
