# Generated by Django 5.1.4 on 2025-01-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_developer_publisher_alter_game_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
