# Generated by Django 5.1.4 on 2025-01-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_game_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='steam_appid',
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='APPID'),
        ),
    ]
