# Generated by Django 5.1.4 on 2025-01-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Резюме'),
        ),
    ]
