# Generated by Django 5.1.4 on 2025-01-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Беслпатная'),
        ),
    ]
